### PR TITLE
Add OpenSSL support to hyper@0.10

### LINKED ISSUE #10: HTTP requests not valid
Seems like my pull request was a little to hasty, I'm getting HTTP errors from what seems to be hyper, but haven't been able to track down the exact issue just yet.

Will look into it, and see if I can identify the problem. Sorry for messing up :disappointed:

The error looks like the following

```rust
NetworkErr(
    Io(
        Error {
            repr: Custom(
                Custom {
                    kind: InvalidInput,
                    error: StringError(
                        "Invalid scheme for Http"
                    )
                }
            )
        }
    )
)
```

### PR DESCRIPTION
**Pull request by oeb25**
This pull request fixes #10, see the issue for details.

### CODE REVIEW

**Comment by phrohdoh** [comment]
Is this a change that tests can be written for?

**Comment by oeb25** [comment]
I was actually looking into that, and think [yup-hyper-mock](https://github.com/Byron/yup-hyper-mock) could be applicable! One issue I encountered, which is the main reason I did not write any tests for it initially, was that the `hyper::Client` [here](https://github.com/Phrohdoh/firebase-rs/pull/11/files#diff-b4aea3e418ccdb71239b96952d9cddb6R351) would need to be tailored specially for the tests, and therefor some sort of dependency-injection would be required. I do have a possible solution in mind that would be backwards compatible, which I possibly could flesh out tomorrow.
Any thoughts?

**Comment by phrohdoh** [comment]
I'm not convinced of mocking but if it isn't too difficult to test locally (and doesn't make our code more complex) then that's fine.

I'll eventually ask you rebase out the 'merge' commit (or I can squash the commits when merged).

**Comment by phrohdoh** [comment]
I will rebase and apply this patch locally if I can fix the build.

**Comment by phrohdoh** [comment]
Would you please provide a sample of broken code?

I've reread the conversations around this and only just now realized you are attempting to use http.
Firebase only supports _https_.

**Comment by oeb25** [comment]
I don't remember exactly, but as far as I recall the issue was that in order to use HTTPS with hyper in the later version, you were to explicitly state that you were using HTTPS trough the OpenSSL package, as shown [here](https://github.com/Phrohdoh/firebase-rs/pull/11/files#diff-b4aea3e418ccdb71239b96952d9cddb6R351). If you read through the [hyper readme](https://github.com/hyperium/hyper), it is at no place stated that they do HTTPS calls, also read the statement in the [v0.10.0 release notes](https://github.com/hyperium/hyper/releases/tag/v0.10.0).

**Comment by phrohdoh** [comment]
I've merged this into master: 2db8ae1d9b7d17f0651e1c3236f6e5bac898f4a8.

Thanks!

**Pull request closed without merging**
